"""
SharedMemory — Central state object shared across all agents.
Every read/write goes through this object.
memory.log(agent, message, level) is the core communication channel.
Level options: INFO | WARN | ERROR | SUCCESS | SURPRISE
"""

import uuid
import datetime
from typing import Any


class SharedMemory:
    """
    Central state object for the multi-agent pipeline.
    
    All agents read from and write to this object exclusively.
    No global variables allowed.
    """

    VALID_LEVELS = {"INFO", "WARN", "ERROR", "SUCCESS", "SURPRISE"}

    def __init__(self) -> None:
        self._state: dict[str, Any] = {
            "project": "Qui queda fora del futur?",
            "run_id": str(uuid.uuid4()),
            "started_at": datetime.datetime.now().isoformat(),

            # Raw datasets (DataFrames)
            "datasets": {
                "oecd_raw": None,
                "oecd_clean": None,
                "eurostat_raw": None,
                "eurostat_clean": None,
                "ine_ccaa_raw": None,
                "ine_ccaa_clean": None,
                "worldbank_researchers": None,
                "ilo_wage_gap": None,
                "desi_digital_skills": None,
                "ine_dementia_mortality": None,
            },

            # Computed metrics
            "metrics": {
                "oecd": {},
                "eurostat": {},
                "ine_ccaa": {},
                "ibtg_index": {},
                "parity_projection": {},
                "surprising_finding": {},
            },

            # Logs and audit
            "pipeline_log": [],
            "cleaning_log": [],
            "audit_results": {},
            "alerts": [],

            # Inter-agent communication
            "feedback_loop": [],         # Skeptic → Cleaner instructions

            # Narrative (StorytellerAgent output)
            "narrative": {},

            # Alternative hypotheses (generated by Storyteller from Skeptic findings)
            "hypotheses": [],

            # Data source coverage (Scout computes this)
            "coverage_score": 0,
            "source_status": {},         # key → {live: bool, year: int, rows: int}
        }

    # ── State access ──────────────────────────────────────────────────────────

    def get(self, key: str, default: Any = None) -> Any:
        """Get a top-level key from state."""
        return self._state.get(key, default)

    def set(self, key: str, value: Any) -> None:
        """Set a top-level key in state."""
        self._state[key] = value

    def get_dataset(self, name: str) -> Any:
        """Get a dataset by name from datasets dict."""
        return self._state["datasets"].get(name)

    def set_dataset(self, name: str, df: Any) -> None:
        """Store a DataFrame in datasets dict."""
        self._state["datasets"][name] = df

    def get_metric(self, section: str) -> dict:
        """Get metrics for a section (oecd, eurostat, ine_ccaa, etc.)."""
        return self._state["metrics"].get(section, {})

    def set_metric(self, section: str, key: str, value: Any) -> None:
        """Set a single metric within a section."""
        if section not in self._state["metrics"]:
            self._state["metrics"][section] = {}
        self._state["metrics"][section][key] = value

    def to_dict(self) -> dict:
        """Export full state as plain dict (for st.session_state storage)."""
        return self._state

    @classmethod
    def from_dict(cls, state: dict) -> "SharedMemory":
        """Restore SharedMemory from a previously exported dict."""
        obj = cls.__new__(cls)
        obj._state = state
        return obj

    # ── Logging ───────────────────────────────────────────────────────────────

    def log(self, agent: str, message: str, level: str = "INFO") -> None:
        """
        Append a structured log entry to pipeline_log.
        
        Args:
            agent:   Name of the calling agent (e.g. "ScoutAgent")
            message: Human-readable message in Catalan
            level:   INFO | WARN | ERROR | SUCCESS | SURPRISE
        """
        if level not in self.VALID_LEVELS:
            level = "INFO"

        entry = {
            "timestamp": datetime.datetime.now().isoformat(),
            "agent": agent,
            "level": level,
            "message": message,
        }
        self._state["pipeline_log"].append(entry)

        # SURPRISE entries get mirrored into metrics.surprising_finding
        if level == "SURPRISE":
            sf = self._state["metrics"].get("surprising_finding", {})
            idx = len(sf)
            sf[f"finding_{idx}"] = {"agent": agent, "message": message}
            self._state["metrics"]["surprising_finding"] = sf

    def add_alert(self, message: str, severity: str = "WARN") -> None:
        """Add to the alerts list (visible in sidebar)."""
        self._state["alerts"].append({"message": message, "severity": severity})

    def add_feedback(self, from_agent: str, to_agent: str,
                     instruction: str, reason: str) -> None:
        """Add a feedback instruction (Skeptic → Cleaner loop)."""
        self._state["feedback_loop"].append({
            "from": from_agent,
            "to": to_agent,
            "instruction": instruction,
            "reason": reason,
            "timestamp": datetime.datetime.now().isoformat(),
        })
